### ISSUE TITLE
Embed Url does not append foward slash (/) at end in README

### ISSUE THREAD

**Issue by sfrostenson** [The-Politico/generator-politico-embeds#4]
When generating the embed code for a graphic it should look like this (generating a https url + a forward slash at the very end of the url):

 ```<div id="federal"></div>
 <script src="//pym.nprapps.org/pym.v1.min.js"></script>
<script>new pym.Parent('federal', 'https://www.politico.com/interactives/2017/embed/state-grid-map/federal/', {})</script>
```

But currently, the embed code is dropping the forward slash at the end and **I believe** is also not generating a https url (I can't remember if the latter is true or not). So currently, the embed code being generated looks like this:

 ```<div id="federal"></div>
 <script src="//pym.nprapps.org/pym.v1.min.js"></script>
<script>new pym.Parent('federal', 'http://www.politico.com/interactives/2017/embed/state-grid-map/federal', {})</script>
```

**Comment by TylerFisher** [comment]
I think this was my fault because I rewrote the README you were working with by hand.
